# Common settings
server:
  port: 8090
spring:
  #profiles: product # Another profile, you can define more profiles as needed
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Sajin@Math1912

  jpa:
    hibernate:
      ddl-auto: update # You might want to change this based on your needs
    database-platform: org.hibernate.dialect.MySQL8Dialect

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    registerWithEureka: true # Eureka Server itself doesn't register
#    fetchRegistry: true # Eureka Server itself doesn't fetch registry
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/


